create table if not exists public.mixtapes (
  id text primary key,
  genre text not null,
  title text not null,
  artwork text not null,
  description text not null,
  audio_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id text primary key,
  month text not null,
  day text not null,
  title text not null,
  details text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_items (
  id text primary key,
  src text not null,
  alt text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.site_videos (
  id text primary key default gen_random_uuid()::text,
  title text not null,
  url text not null,
  type text not null default 'youtube',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key default 'default',
  hero_title text not null default 'INT''L DJ EXPERIENCE',
  hero_subtitle text not null default 'Live energy. Deep culture. Unforgettable nights.',
  hero_image text not null default '/Hero-view.jpg',
  about_eyebrow text not null default 'INT''L DJ EXPERIENCE',
  about_title text not null default 'About Me',
  about_image text not null default 'https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=1000&q=85',
  about_image_alt text not null default 'Int''L DJ Experience performer',
  about_paragraphs text[] not null default ARRAY[
    'Int''L DJ Experience, known legally as Dapaah Jerry John, is a versatile Ghanaian disk jockey, entertainer, and professional website developer.',
    'Popularly crowned the Campus DJ, he has built a strong reputation across the Ghanaian entertainment circuit for his high-energy live performances and viral digital mixtapes. Jerry balances his passion for music with a deep background in technology. He is currently studying Information and Communications Technology (ICT) at the University of Education, Winneba (UEW). By uniquely merging his technical skills as a web developer with his musical creativity, Int''L DJ Experience is paving a distinct path as a modern, self-reliant tech-and-entertainment brand in the digital music era.'
  ],
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  event_type text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null default 'Guest',
  mood text not null default 'neutral' check (mood in ('good', 'bad', 'neutral')),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.mixtapes enable row level security;
alter table public.events enable row level security;
alter table public.gallery_items enable row level security;
alter table public.site_videos enable row level security;
alter table public.site_settings enable row level security;
alter table public.bookings enable row level security;
alter table public.comments enable row level security;

create policy "Public can read mixtapes"
  on public.mixtapes for select to anon, authenticated using (true);

create policy "Public can read events"
  on public.events for select to anon, authenticated using (true);

create policy "Public can read gallery"
  on public.gallery_items for select to anon, authenticated using (true);

create policy "Public can read videos"
  on public.site_videos for select to anon, authenticated using (true);

create policy "Public can read site settings"
  on public.site_settings for select to anon, authenticated using (true);

create policy "Authenticated users can manage site settings"
  on public.site_settings for all to authenticated using (true) with check (true);

create policy "Authenticated users can manage videos"
  on public.site_videos for all to authenticated using (true) with check (true);

create or replace view public.public_site_videos as
select * from public.site_videos;

insert into public.mixtapes (id, genre, title, artwork, description, audio_url)
values
  ('afrobeats-vibes-01', 'Afrobeats', 'Afrobeats Vibes Vol. 01', 'https://images.unsplash.com/photo-1571266028243-d220c19c9f4c?auto=format&fit=crop&w=800&q=85', 'A vibrant selection of African sounds and late-night energy.', null),
  ('amapiano-groove', 'Amapiano', 'Amapiano Groove', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=85', 'A smooth journey through deep grooves and dance-floor rhythms.', null)
on conflict (id) do nothing;

insert into public.events (id, month, day, title, details, sort_order)
values
  ('urban-night-accra', 'SEP', '18', 'Urban Night - Accra', 'Live DJ set - 9:00 PM', 1),
  ('afro-culture-party-kumasi', 'OCT', '03', 'Afro Culture Party - Kumasi', 'Guest DJ - 8:00 PM', 2),
  ('private-experience', 'OCT', '24', 'Private Experience', 'Booking - Location TBA', 3)
on conflict (id) do nothing;

insert into public.gallery_items (id, src, alt, sort_order)
values
  ('live-performance', 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=700&q=85', 'DJ performance at a live event', 1),
  ('crowd-moment', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=700&q=85', 'Crowd enjoying a DJ set', 2),
  ('outdoor-event', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=700&q=85', 'Audience at an outdoor music event', 3),
  ('performance-detail', 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=700&q=85', 'DJ equipment and performance moment', 4)
on conflict (id) do nothing;

insert into public.site_settings (id, hero_title, hero_subtitle, hero_image, about_eyebrow, about_title, about_image, about_image_alt, about_paragraphs)
values (
  'default',
  'INT''L DJ EXPERIENCE',
  'Live energy. Deep culture. Unforgettable nights.',
  '/Hero-view.jpg',
  'INT''L DJ EXPERIENCE',
  'About Me',
  'https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=1000&q=85',
  'Int''L DJ Experience performer',
  ARRAY[
    'Int''L DJ Experience, known legally as Dapaah Jerry John, is a versatile Ghanaian disk jockey, entertainer, and professional website developer.',
    'Popularly crowned the Campus DJ, he has built a strong reputation across the Ghanaian entertainment circuit for his high-energy live performances and viral digital mixtapes. Jerry balances his passion for music with a deep background in technology. He is currently studying Information and Communications Technology (ICT) at the University of Education, Winneba (UEW). By uniquely merging his technical skills as a web developer with his musical creativity, Int''L DJ Experience is paving a distinct path as a modern, self-reliant tech-and-entertainment brand in the digital music era.'
  ]
)
on conflict (id) do nothing;
