-- Run this migration in the Supabase SQL Editor for the production project.
-- It is safe to run more than once.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null default 'Guest',
  email text not null,
  mood text not null default 'neutral' check (mood in ('good', 'bad', 'neutral')),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.comments add column if not exists email text;
update public.comments set email = 'unknown@example.com' where email is null;
alter table public.comments alter column email set not null;
alter table public.comments alter column email drop not null;
alter table public.comments alter column mood drop not null;
alter table public.comments alter column name set default 'Anonymous';
alter table public.comments add column if not exists likes integer not null default 0;
alter table public.comments add column if not exists avatar_url text;

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

alter table public.comment_likes enable row level security;

create table if not exists public.comment_replies (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.comment_replies enable row level security;
alter table public.comment_replies alter column user_id drop not null;
alter table public.comment_replies add column if not exists avatar_url text;
alter table public.comment_replies alter column name set default 'Anonymous';

create table if not exists public.email_verifications (
  token uuid primary key,
  email text not null,
  purpose text not null check (purpose in ('booking', 'comment')),
  code_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.email_verifications enable row level security;

alter table public.comments enable row level security;

drop policy if exists "Public can read comments" on public.comments;
create policy "Public can read comments"
  on public.comments for select to anon, authenticated using (true);

drop policy if exists "Authenticated users can manage comment likes" on public.comment_likes;
create policy "Authenticated users can manage comment likes"
  on public.comment_likes for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "Public can read comment replies" on public.comment_replies;
create policy "Public can read comment replies"
  on public.comment_replies for select to anon, authenticated using (true);

drop policy if exists "Authenticated users can create comment replies" on public.comment_replies;
create policy "Authenticated users can create comment replies"
  on public.comment_replies for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Public can submit comments" on public.comments;
create policy "Public can submit comments"
  on public.comments for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read comments" on public.comments;
create policy "Admins can read comments"
  on public.comments for select
  to authenticated
  using (exists (
    select 1 from public.admin_users where user_id = auth.uid()
  ));