create table if not exists public.mixtapes (
  id text primary key,
  genre text not null,
  title text not null,
  artwork text not null,
  description text not null,
  audio_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id text primary key,
  month text not null,
  day text not null,
  title text not null,
  details text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_items (
  id text primary key,
  src text not null,
  alt text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  event_type text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null default 'Guest',
  mood text not null default 'neutral' check (mood in ('good', 'bad', 'neutral')),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.mixtapes enable row level security;
alter table public.events enable row level security;
alter table public.gallery_items enable row level security;
alter table public.bookings enable row level security;
alter table public.comments enable row level security;

create policy "Public can read mixtapes"
  on public.mixtapes for select to anon, authenticated using (true);

create policy "Public can read events"
  on public.events for select to anon, authenticated using (true);

create policy "Public can read gallery"
  on public.gallery_items for select to anon, authenticated using (true);

insert into public.mixtapes (id, genre, title, artwork, description, audio_url)
values
  ('afrobeats-vibes-01', 'Afrobeats', 'Afrobeats Vibes Vol. 01', 'https://images.unsplash.com/photo-1571266028243-d220c19c9f4c?auto=format&fit=crop&w=800&q=85', 'A vibrant selection of African sounds and late-night energy.', null),
  ('amapiano-groove', 'Amapiano', 'Amapiano Groove', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=85', 'A smooth journey through deep grooves and dance-floor rhythms.', null)
on conflict (id) do nothing;

insert into public.events (id, month, day, title, details, sort_order)
values
  ('urban-night-accra', 'SEP', '18', 'Urban Night - Accra', 'Live DJ set - 9:00 PM', 1),
  ('afro-culture-party-kumasi', 'OCT', '03', 'Afro Culture Party - Kumasi', 'Guest DJ - 8:00 PM', 2),
  ('private-experience', 'OCT', '24', 'Private Experience', 'Booking - Location TBA', 3)
on conflict (id) do nothing;

insert into public.gallery_items (id, src, alt, sort_order)
values
  ('live-performance', 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=700&q=85', 'DJ performance at a live event', 1),
  ('crowd-moment', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=700&q=85', 'Crowd enjoying a DJ set', 2),
  ('outdoor-event', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=700&q=85', 'Audience at an outdoor music event', 3),
  ('performance-detail', 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=700&q=85', 'DJ equipment and performance moment', 4)
on conflict (id) do nothing;
